### ISSUE TITLE
Starting bot

### ISSUE THREAD

**Issue by oskargehringer** [surfranch/TelegramShillBot#1]
First of all, thank you for this bot!

My question is, how can I change the formatting so that the bot would let me use telegram emojis in my text?

Thank you in advance and greetings from Austria. :)

**Comment by oskargehringer** [comment]
wanted to add that there is no promt or anything... everything seems to be installed correctly but the bot just doesn't run and does chat postings.

**Comment by oskargehringer** [comment]
This is the output text:

Traceback (most recent call last):
  File "/app/tg_shill_bot.py", line 12, in <module>
    CONFIG = yaml.safe_load(settings)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "settings.yml", line 13, column 12

**Comment by oskargehringer** [comment]
![problem](https://user-images.githubusercontent.com/88940103/131253141-87773466-40a7-4fbe-a519-cc1bd48c7292.PNG)
Everytime I hit docker run shil in cmd, a new image/container (I have no clue) starts and finishes after one sec.

**Comment by oskargehringer** [comment]
Now I also tried the "hard way", all packages installed, this is what is says when I start the bot: 
![hardway](https://user-images.githubusercontent.com/88940103/131257305-991c567a-a6b1-48a2-b26f-2fc67a407f7b.PNG)

**Comment by EnorMOZ** [comment]
Simple copy and paste should work ie:
```
long: | 
    😴 My Token 🎂
    Antiwhale 🐳 
    Anti dump 🗑
    Based dev 🙌 
    Anti snipe 😜
    Kraken 🐙

**Comment by oskargehringer** [comment]
I tried that but it still sends out error. Also copied emoticons from websites that are supposed to work (https://apps.timwhitlock.info/emoji/tables/unicode#block-3-transport-and-map-symbols)

**Comment by EnorMOZ** [comment]
> I tried that but it still sends out error. Also copied emoticons from websites that are supposed to work (https://apps.timwhitlock.info/emoji/tables/unicode#block-3-transport-and-map-symbols)
<img width="760" alt="Screen Shot 2021-08-30 at 9 20 43 AM" src="https://user-images.githubusercontent.com/13998170/131345575-977f23c9-5316-4538-b8ac-82f30bf93404.png">

What error are you getting ?

**Comment by oskargehringer** [comment]
That one:

(venv) C:\Users\Vikto\source\repos\TelegramShillBot>python tg_shill_bot.py
Traceback (most recent call last):
  File "tg_shill_bot.py", line 12, in <module>
    CONFIG = yaml.safe_load(settings)
  File "C:\Users\Vikto\source\repos\TelegramShillBot\venv\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Vikto\source\repos\TelegramShillBot\venv\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Users\Vikto\source\repos\TelegramShillBot\venv\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Vikto\source\repos\TelegramShillBot\venv\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\Vikto\source\repos\TelegramShillBot\venv\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\Vikto\source\repos\TelegramShillBot\venv\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\Vikto\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 162: character maps to <undefined>

**Comment by EnorMOZ** [comment]
Can you paste the message that is giving you issues ? Also have you tried a single emoticon in your message to see if that works for you?

**Comment by oskargehringer** [comment]
I tried it with your message and it outputs the same error as with my messages. Exact settings.yml from the error (without api and stuff): 

messages:
  long: |
    😴 My Token 🎂
    Antiwhale 🐳 
    Anti dump 🗑
    Based dev 🙌 
    Anti snipe 😜
    Kraken 🐙

  short: |
       😴 My Token 🎂
    Antiwhale 🐳 
    Anti dump 🗑
    Based dev 🙌 
    Anti snipe 😜
    Kraken 🐙

raid:
  BSCDefiExperts:
    message_type: long
    wait_interval: 300
  CryptoM00NShot:
    message_type: short
    wait_interval: 300



And yes, with only one or only a few emojis it works.

**Comment by EnorMOZ** [comment]
Paste your settings.yml here and see if it gives you any errors. http://www.yamllint.com/

**Comment by oskargehringer** [comment]
No it returns (with my original message): (<unknown>): mapping values are not allowed in this context at line 3 column 12

**Comment by EnorMOZ** [comment]
Ping me on TG same name as here.

**Comment by oskargehringer** [comment]
Great thank you! :)

**Comment by EnorMOZ** [comment]
Issue resolved, was due to bad yaml

**Comment by gkspranger** [comment]
encoding issues should be fixed with this commit :: https://github.com/surfranch/TelegramShillBot/commit/b4f96625cc5d9f85e2de47303b8103048aecd3cd
