### ISSUE TITLE
Traceback error with latest version

### ISSUE THREAD

**Issue by oskargehringer** [surfranch/TelegramShillBot#12]
Hey there,
I'm getting the following error that I did not get with the version before. In the previous version, the bot somehow simply does not send to that group and there is no error. I see what the error means but would it be possible to catch it and make the bot send again to that group once the required wait time is over? The error:

[15:15:38.153] Sending message to BSCApe
Traceback (most recent call last):
  File "/app/tg_shill_bot.py", line 149, in <module>
    LOOP.run_until_complete(start())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/tg_shill_bot.py", line 142, in start
    await do_raid()
  File "/app/tg_shill_bot.py", line 119, in do_raid
    await asyncio.gather(*tasks)
  File "/app/tg_shill_bot.py", line 102, in raid
    await send_message(channel)
  File "/app/tg_shill_bot.py", line 86, in send_message
    await CLIENT.send_message(entity, new_message)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/messages.py", line 853, in send_message
    result = await self(request)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.SlowModeWaitError: A wait of 559 seconds is required before sending another message in this chat (caused by SendMessageRequest)

Thanks in advance.

**Comment by EnorMOZ** [comment]
@oskargehringer See if the latest commit helps.

**Comment by gkspranger** [comment]
this has been fixed with this commit

https://github.com/surfranch/TelegramShillBot/commit/6a5911ec02c2d9888879b1469220fbe0839e28db
