### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by gfirst20** [surfranch/TelegramShillBot#24]
i ran with python and go this error message

Traceback (most recent call last):
  File "tg_shill_bot.py", line 149, in <module>
    CLIENT = TelegramClient(APP_SHORT_NAME, API_ID, API_HASH)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/telegrambaseclient.py", line 299, in __init__
    self.api_id = int(api_id)
ValueError: invalid literal for int() with base 10: '1d491ef9d3521e4be434f0483d6a6d60'

Please help

**Comment by gkspranger** [comment]
same as this issue

https://github.com/surfranch/TelegramShillBot/issues/22
