### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Monikajosa** [surfranch/TelegramShillBot#40]
get a lot of these error messages

Security error while unpacking a received message: Server replied with a wrong session ID
and
Unhandled error while processing msgs
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 540, in _recv_loop
    await self._process_message(message)
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 555, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 601, in _handle_rpc_result
    if not isinstance(reader.tgread_object(), upload.File):
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 120, in tgread_object
    constructor_id = self.read_int(signed=False)
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 37, in read_int
    return int.from_bytes(self.read(4), byteorder='little', signed=signed)
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 60, in read
    raise BufferError(
BufferError: No more data left to read (need 4, got 0: b''); last read None
Invalid buffer Invalid response buffer (HTTP code 429)

can someone help pls?

**Comment by gkspranger** [comment]
this usually happens when trying to reuse a TG session .. it typically can be fixed by:
- stopping the bot
- removing all `*.session` files
- starting the bot back up

also make sure your current internet connection is able to reach TG -- as we have heard of people having issues when they setup some kind of custom, local proxy setup
